services:
  backend:
    build: ./backend
    container_name: homectl-backend
    ports:
      - "3000:3000"
    restart: unless-stopped

  frontend:
    build: ./apache
    container_name: homectl-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
